group_homepage:
    path:     /group
    defaults: { _controller: 'GroupBundle:Group:index' }

group_create:
    path:     /group/new
    defaults: { _controller: 'GroupBundle:Group:createGroup' }    

group_edit:
    path:     /group/edit
    defaults: { _controller: 'GroupBundle:Group:editGroup' }    
    
group_sessions:
    path:     /group/sessions
    defaults: { _controller: 'GroupBundle:Group:sessionsGroup' }   
    
group_checkGroupName:
    path:     /group/checkname
    defaults: { _controller: 'GroupBundle:Group:checkGroupByName' }            