group_homepage:
    path:     /group
    defaults: { _controller: 'GroupBundle:Group:index' }

group_create:
    path:     /group/new
    defaults: { _controller: 'GroupBundle:Group:createGroup' }   
    
group_savenewgroup:
    path:     /group/savenewgroup
    defaults: { _controller: 'GroupBundle:Group:saveNewGroup' }        

group_edit:
    path:     /group/edit
    defaults: { _controller: 'GroupBundle:Group:editGroup' }    
    
group_sessions:
    path:     /group/sessions
    defaults: { _controller: 'GroupBundle:Group:sessionsGroup' }   
    
group_checkgroupname:
    path:     /group/checkname
    defaults: { _controller: 'GroupBundle:Group:checkGroupByName' }            

group_loadallgroups:
    path:     /group/loadallgroups
    defaults: { _controller: 'GroupBundle:Group:loadAllGroups' }  

group_loadgroupsbystatus:
    path:     /group/loadgroupsbystatus
    defaults: { _controller: 'GroupBundle:Group:loadGroupsByStatus' }  

group_uploadimage:    
    path:     /group/loadimagegroup
    defaults: { _controller: 'GroupBundle:Group:loadImageGroup' }  
       