session_homepage:
    path:     /session
    defaults: { _controller: 'SessionBundle:Session:index' }
    
session_mysessions:    
    path:     /session/mine
    defaults: { _controller: 'SessionBundle:Session:mySessions' }
    
session_new:
    path:     /session/new
    defaults: { _controller: 'SessionBundle:Session:newSession' }

session_checksessionname:
    path:     /session/checkname
    defaults: { _controller: 'SessionBundle:Session:checkSessionByName' }   
    
session_save:
    path:     /session/save
    defaults: { _controller: 'SessionBundle:Session:saveSession' }         
    
session_loadsessionbystatus:
    path:     /session/loadsessionbystatus
    defaults: { _controller: 'SessionBundle:Session:loadSessionByStatus' }        