profile_homepage:
    path:     /profile
    defaults: { _controller: 'ProfileBundle:Profile:index' }

profile_new:
    path:     /profile/new
    defaults: { _controller: 'ProfileBundle:Profile:new' }       

profile_edit:
    path:     /profile/edit
    defaults: { _controller: 'ProfileBundle:Profile:edit' }
    
profile_checkemail:
    path: /profile/checkemail
    defaults: { _controller: 'ProfileBundle:Profile:checkEmail' }

profile_checkshortname:
    path: /profile/checkshortname
    defaults: { _controller: 'ProfileBundle:Profile:checkShortName' }
    
profile_loginUser:
    path:     /checkLoginUser
    defaults: { _controller: 'ProfileBundle:Profile:loginUser' }     
    
profile_loadallusers:          
    path:     /profile/loadallusers
    defaults: { _controller: 'ProfileBundle:Profile:loadAllUsers' }     
