profile_homepage:
    path:     /profile
    defaults: { _controller: 'ProfileBundle:Profile:index' }

profile_edit:
    path:     /profile/edit
    defaults: { _controller: 'ProfileBundle:Profile:edit' }
    
profile_checkemail:
    path: /profile/checkemail
    defaults: { _controller: 'ProfileBundle:Profile:checkEmail' }   
