profile_homepage:
    path:     /profile
    defaults: { _controller: 'ProfileBundle:Profile:index' }

profile_new:
    path:     /profile/new
    defaults: { _controller: 'ProfileBundle:Profile:new' }       

profile_edit:
    path:     /profile/edit
    defaults: { _controller: 'ProfileBundle:Profile:edit' }

profile_loaduser:
    path:     /profile/loaduser
    defaults: { _controller: 'ProfileBundle:Profile:loadUser' }

profile_saveuser:
    path:     /profile/saveuser
    defaults: { _controller: 'ProfileBundle:Profile:saveUser' }

profile_changepassword:
    path:     /profile/changepassword
    defaults: { _controller: 'ProfileBundle:Profile:changePassword' }

profile_savechangedpassword:
    path:     /profile/savechangedpassword
    defaults: { _controller: 'ProfileBundle:Profile:saveChangedPassword' }
    
profile_cancelprofile:
    path:     /profile/cancelprofile
    defaults: { _controller: 'ProfileBundle:Profile:cancelProfile' }
 
profile_canceledprofile:
    path:     /profile/canceledprofile
    defaults: { _controller: 'ProfileBundle:Profile:calceledProfile' } 
    
profile_checkemail:
    path: /profile/checkemail
    defaults: { _controller: 'ProfileBundle:Profile:checkEmail' }

profile_checkshortname:
    path: /profile/checkshortname
    defaults: { _controller: 'ProfileBundle:Profile:checkShortName' }
    
profile_loginUser:
    path:     /checkLoginUser
    defaults: { _controller: 'ProfileBundle:Profile:loginUser' }     
    
profile_loadallusers:          
    path:     /profile/loadallusers
    defaults: { _controller: 'ProfileBundle:Profile:loadAllUsers' }     
