services:
#    profile.example:
#        class: ProfileBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     profile.services:
        class: ProfileBundle\Service\ProfileService
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container", "@logger" ] 
