imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@SessionBundle/Resources/config/services.yml" }
    - { resource: "@ProfileBundle/Resources/config/services.yml" }
    - { resource: "@FeedBundle/Resources/config/services.yml" }
    - { resource: "@SearchBundle/Resources/config/services.yml" }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@ChatBundle/Resources/config/services.yml" }
    - { resource: "@GroupBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pt_br
    
    group_images_directory: '%kernel.root_dir%/../web/uploads/groupimages'
    profile_images_directory: '%kernel.root_dir%/../web/uploads/profileimages'
    session_images_directory: '%kernel.root_dir%/../web/uploads/sessionimages'
    
framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: tagarelas
        connections:
  
          tagarelas:
            driver:   "%database_driver%"
            host:     "%database_host%"
            port:     "%database_port%"
            dbname:   "%database_name%"
            user:     "%database_user%"
            password: "%database_password%"
            charset:  UTF8 
             

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true
        default_entity_manager: tagarelas
        
        entity_managers:
              
          tagarelas:    
            connection: tagarelas
            mappings:
              AppBundle:                     
                  type: annotation
                  prefix: AppBundle\Openfire
                  dir: "%kernel.root_dir%/../src/AppBundle/Openfire"
        
# Rotas de AJAX
fos_js_routing:
    routes_to_expose: [  ]
            
# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    username:  "%tagarelas.comunicatec@gmail.com"
    password:  "P1m&nT&l"
    
 #FOSMessage
fos_message:
    db_driver: orm
    thread_class:      "AppBundle/Openfire/Entity/Thread"
    message_class:  " AppBundle/Openfire/Entity/Message"
#   spam_detector:  "fos_message.akismet_spam_detector"
    
    
# FOSUser
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: "AppBundle/Openfire/Entity/User"
    from_email:
        address: tagarelas.comunicatec@gmail.com
        sender_name: "Equipe Tagarelas" 
    
hwi_oauth:
    firewall_names: [secured_area] 

    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_client_id%"
            client_secret:       "%facebook_client_secret%"
            scope:               "email profile"
            options:
                display: popup #dialog is optimized for popup window
                auth_type: rerequest # Re-asking for Declined Permissions
        
        google:
            type:                google
            client_id:           "%google_client_id%"
            client_secret:       "%google_client_secret%"
            scope:               "email profile"
            options:
                access_type:     "offline"

    http_client:
        verify_peer: false           