group:
    resource: "@GroupBundle/Resources/config/routing.yml"
    prefix:   /

chat:
    resource: "@ChatBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

search:
    resource: "@SearchBundle/Resources/config/routing.yml"
    prefix:   /

feed:
    resource: "@FeedBundle/Resources/config/routing.yml"
    prefix:   /

profile:
    resource: "@ProfileBundle/Resources/config/routing.yml"
    prefix:   /

session:
    resource: "@SessionBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
      
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login   

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google
    
the:
    resource: "@TheBundle/Resources/config/routing.yml"
    prefix:   /  

# fos_user routing
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
  
logout:
    path: /logout
       
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml" 

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /optional_routing_prefix    