about:
    resource: "@AboutBundle/Controller/"
    type:     annotation
    prefix:   /


admin:
    resource: "@AdminBundle/Controller/AdminController.php"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

chat:
    resource: "@ChatBundle/Controller/ChatController.php"
    type:     annotation

feed:
    resource: "@FeedBundle/Controller/FeedController.php"
    type:     annotation

group:
    resource: "@GroupBundle/Controller/GroupController.php"
    type:     annotation

profile:
    resource: "@ProfileBundle/Controller/ProfileController.php"
    type:     annotation

search:
    resource: "@SearchBundle/Controller/SearchController.php"
    type:     annotation
    
session:
    resource: "@SessionBundle/Controller/SessionController.php"
    type:     annotation


#--------------------------------------------
# Vendor Area
#--------------------------------------------

# fos_user routing
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# hwi_oauth routing     
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /redirect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /logon   

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google
    
the:
    resource: "@TheBundle/Resources/config/routing.yml"
    prefix:   /the  



  

