# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

         
    providers:

        fos_userbundle:
            id: fos_user.user_provider.username
            
        in_memory:
            memory: ~

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: false
                default_target_path: /menu
            logout:      
                target: /login
            anonymous:  true
            switch_user: true
            
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~

        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                    my_custom_provider: "/login/check-custom"
                    my_github:          "/login/check-github"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: my.oauth_aware.user_provider.servic

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
          my_custom_hwi_provider:
            id: hwi_oauth.user.provider.entity

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider:  my_custom_hwi_provider
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
            
        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                login_path:             /login
                use_forward:           false
                failure_path:          "/login"

                oauth_user_provider:
                    service:  my.oauth_aware.user_provider.service

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }