# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

     hwi_oauth.user.provider.entity:
        class: CodeMe\TheBundle\Provider\Provider
        arguments: ["@session", "@doctrine", "@admin.checker", "@request_stack"]
     
     admin.checker:
        class: CodeMe\TheBundle\Provider\AdminChecker
        arguments: ["@doctrine", "%admins%"]
        
     mailer.services:
        class: AppBundle\Utility\Mailer
        arguments: [ "@service_container", "@logger" ]  
      
      # ------------------------------
      # Services de FOSMessages
      #-------------------------------
      
     fos_message.driver:
        class:  FOS\Message\Driver\Doctrine\ORM\DoctrineORMDriver
        arguments:  [ "@doctrine.orm.entity_manager" ]

     fos_message.repository:
        class:  FOS\Message\Repository
        arguments:  [ "@fos_message.driver" ]

     fos_message.event_dispatcher:
        class:  FOS\Message\EventDispatcher\SymfonyBridgeEventDispatcher
        arguments:  [ "@event_dispatcher" ]

     fos_message.tagger:
        class:  FOS\Message\Tagger 
        arguments:
            -  "@fos_message.driver"
            -  "@fos_message.repository"

     fos_message.sender:
        class:  FOS\Message\Sender
        arguments:
            -  "@fos_message.driver"
            -  "@fos_message.event_dispatcher"