# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

     hwi_oauth.user.provider.entity:
        class: CodeMe\TheBundle\Provider\Provider
        arguments: ["@session", "@doctrine", "@admin.checker", "@request_stack"]
     
     admin.checker:
        class: CodeMe\TheBundle\Provider\AdminChecker
        arguments: ["@doctrine", "%admins%"]
        
     mailer.services:
        class: AppBundle\Utility\Mailer
        arguments: [ "@service_container", "@logger" ]     